name: Testing the application

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@vv5.0.0
            - name: Setup NodeJS
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Build the application
              run: npm run build
    test:
        name: Test
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@vv5.0.0
            - name: Setup NodeJS
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 20.x
            - name: Install dependencies
              run: npm ci
            - name: Test the application
              run: npm run test
