name: Testing the application

on:
    push:
        branches:
            - main

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5.0.0
            - name: Setup NodeJS
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 20.x
            - name: Install dependencies
              run: npm install
            - name: Build the application
              run: npm run build
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5.0.0
            - name: Setup NodeJS
              uses: actions/setup-node@v4.4.0
              with:
                node-version: 20.x
            - name: Install dependencies
              run: npm install
            - name: Test the application
              run: npm run test
    docker:
        name: Docker
        needs: [build, test]
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the code
              uses: actions/checkout@v5.0.0
            - name: Create .env-File
              run: cp .env.prod.example .env
            - name: Build the container
              run: docker build -t poke-stats-app ./
            - name: Running the container
              run: docker run -d -p 80:80 --name poke-stats-container poke-stats-app
            - name: Stop the container
              run: docker stop poke-stats-container
            - name: Remove the container
              run: docker rm poke-stats-container
